# This file is automatically generated from cmake-kits.json and should be modified only if compiling from CLI
if (NOT DEFINED ENV{ARMGCC_DIR})
	SET(ARMGCC_DIR /Applications/MCUXpressoIDE_11.9.1_2170/ide/tools)
endif()
